from __future__ import annotations

DEFAULT_BOT_ICON = "robot"
BOT_ICON_KEYS: tuple[str, ...] = (
    # Faces & characters
    "robot",
    "alien",
    "ghost",
    "skull",
    "clown",
    "wizard",
    "ninja",
    "santa",
    "detective",
    # Animals
    "dog",
    "cat",
    "fox",
    "bear",
    "owl",
    "eagle",
    "wolf",
    "lion",
    "dragon",
    "unicorn",
    "dolphin",
    "whale",
    "octopus",
    "butterfly",
    "bee",
    "ant",
    "spider",
    "snail",
    "penguin",
    "parrot",
    # Objects & tools
    "briefcase",
    "code",
    "search",
    "test-tube",
    "shield",
    "sparkles",
    "chat",
    "brain",
    "rocket",
    "star",
    "fire",
    "lightning",
    "gem",
    "crown",
    "key",
    "lock",
    "magnifier",
    "wrench",
    "hammer",
    "gear",
    "compass",
    "telescope",
    "microscope",
    "flask",
    "atom",
    "satellite",
    "antenna",
    "printer",
    "database",
    "globe",
    "building",
    "hospital",
    "school",
    "library",
    "book",
    "pen",
    "pencil",
    "paintbrush",
    "palette",
    "camera",
    "film",
    "music",
    "headphones",
    "microphone",
    "gamepad",
    "dice",
    "chess",
    "trophy",
    "medal",
    "flag",
    "wand",
    "crystal",
    "candle",
    "hourglass",
    "clock",
    # Nature & weather
    "sun",
    "moon",
    "rainbow",
    "cloud",
    "snowflake",
    "tornado",
    "wave",
    "mountain",
    "tree",
    "flower",
    "seedling",
    "mushroom",
    "leaf",
    "cactus",
    # Food & drink
    "coffee",
    "pizza",
    "taco",
    "ice-cream",
    "cookie",
    "candy",
    "fruit",
    "avocado",
    # Misc
    "heart",
    "party",
    "balloon",
    "gift",
    "pin",
    "paperclip",
    "bulb",
    "megaphone",
    "bell",
    "no-bell",
    "link",
    "chain",
    "anchor",
    "plane",
    "car",
    "train",
    "ship",
    "umbrella",
    "map",
    "pinwheel",
)


def validate_bot_icon(icon: str) -> str:
    if icon not in BOT_ICON_KEYS:
        raise ValueError(f"icon must be one of: {', '.join(BOT_ICON_KEYS)}")
    return icon
