export interface BotIconOption { key: string; label: string; glyph: string; }

export const DEFAULT_BOT_ICON = "robot";
export const BOT_ICONS: BotIconOption[] = [
  // Faces & characters
  { key: "robot", label: "Robot", glyph: "🤖" },
  { key: "alien", label: "Alien", glyph: "👽" },
  { key: "ghost", label: "Ghost", glyph: "👻" },
  { key: "skull", label: "Skull", glyph: "💀" },
  { key: "clown", label: "Clown", glyph: "🤡" },
  { key: "wizard", label: "Wizard", glyph: "🧙" },
  { key: "ninja", label: "Ninja", glyph: "🥷" },
  { key: "santa", label: "Santa", glyph: "🎅" },
  { key: "detective", label: "Detective", glyph: "🕵️" },
  // Animals
  { key: "dog", label: "Dog", glyph: "🐶" },
  { key: "cat", label: "Cat", glyph: "🐱" },
  { key: "fox", label: "Fox", glyph: "🦊" },
  { key: "bear", label: "Bear", glyph: "🐻" },
  { key: "owl", label: "Owl", glyph: "🦉" },
  { key: "eagle", label: "Eagle", glyph: "🦅" },
  { key: "wolf", label: "Wolf", glyph: "🐺" },
  { key: "lion", label: "Lion", glyph: "🦁" },
  { key: "dragon", label: "Dragon", glyph: "🐉" },
  { key: "unicorn", label: "Unicorn", glyph: "🦄" },
  { key: "dolphin", label: "Dolphin", glyph: "🐬" },
  { key: "whale", label: "Whale", glyph: "🐳" },
  { key: "octopus", label: "Octopus", glyph: "🐙" },
  { key: "butterfly", label: "Butterfly", glyph: "🦋" },
  { key: "bee", label: "Bee", glyph: "🐝" },
  { key: "ant", label: "Ant", glyph: "🐜" },
  { key: "spider", label: "Spider", glyph: "🕷️" },
  { key: "snail", label: "Snail", glyph: "🐌" },
  { key: "penguin", label: "Penguin", glyph: "🐧" },
  { key: "parrot", label: "Parrot", glyph: "🦜" },
  // Objects & tools
  { key: "briefcase", label: "Briefcase", glyph: "💼" },
  { key: "code", label: "Code", glyph: "💻" },
  { key: "search", label: "Search", glyph: "🔎" },
  { key: "test-tube", label: "Test tube", glyph: "🧪" },
  { key: "shield", label: "Shield", glyph: "🛡️" },
  { key: "sparkles", label: "Sparkles", glyph: "✨" },
  { key: "chat", label: "Chat", glyph: "💬" },
  { key: "brain", label: "Brain", glyph: "🧠" },
  { key: "rocket", label: "Rocket", glyph: "🚀" },
  { key: "star", label: "Star", glyph: "⭐" },
  { key: "fire", label: "Fire", glyph: "🔥" },
  { key: "lightning", label: "Lightning", glyph: "⚡" },
  { key: "gem", label: "Gem", glyph: "💎" },
  { key: "crown", label: "Crown", glyph: "👑" },
  { key: "key", label: "Key", glyph: "🔑" },
  { key: "lock", label: "Lock", glyph: "🔒" },
  { key: "magnifier", label: "Magnifier", glyph: "🔍" },
  { key: "wrench", label: "Wrench", glyph: "🔧" },
  { key: "hammer", label: "Hammer", glyph: "🔨" },
  { key: "gear", label: "Gear", glyph: "⚙️" },
  { key: "compass", label: "Compass", glyph: "🧭" },
  { key: "telescope", label: "Telescope", glyph: "🔭" },
  { key: "microscope", label: "Microscope", glyph: "🔬" },
  { key: "flask", label: "Flask", glyph: "⚗️" },
  { key: "atom", label: "Atom", glyph: "⚛️" },
  { key: "satellite", label: "Satellite", glyph: "🛰️" },
  { key: "antenna", label: "Antenna", glyph: "📡" },
  { key: "printer", label: "Printer", glyph: "🖨️" },
  { key: "database", label: "Database", glyph: "🗄️" },
  { key: "globe", label: "Globe", glyph: "🌍" },
  { key: "building", label: "Building", glyph: "🏢" },
  { key: "hospital", label: "Hospital", glyph: "🏥" },
  { key: "school", label: "School", glyph: "🏫" },
  { key: "library", label: "Library", glyph: "📚" },
  { key: "book", label: "Book", glyph: "📖" },
  { key: "pen", label: "Pen", glyph: "🖊️" },
  { key: "pencil", label: "Pencil", glyph: "✏️" },
  { key: "paintbrush", label: "Paintbrush", glyph: "🖌️" },
  { key: "palette", label: "Palette", glyph: "🎨" },
  { key: "camera", label: "Camera", glyph: "📷" },
  { key: "film", label: "Film", glyph: "🎬" },
  { key: "music", label: "Music", glyph: "🎵" },
  { key: "headphones", label: "Headphones", glyph: "🎧" },
  { key: "microphone", label: "Microphone", glyph: "🎤" },
  { key: "gamepad", label: "Gamepad", glyph: "🎮" },
  { key: "dice", label: "Dice", glyph: "🎲" },
  { key: "chess", label: "Chess", glyph: "♟️" },
  { key: "trophy", label: "Trophy", glyph: "🏆" },
  { key: "medal", label: "Medal", glyph: "🏅" },
  { key: "flag", label: "Flag", glyph: "🚩" },
  { key: "wand", label: "Wand", glyph: "🪄" },
  { key: "crystal", label: "Crystal ball", glyph: "🔮" },
  { key: "candle", label: "Candle", glyph: "🕯️" },
  { key: "hourglass", label: "Hourglass", glyph: "⏳" },
  { key: "clock", label: "Clock", glyph: "⏰" },
  // Nature & weather
  { key: "sun", label: "Sun", glyph: "☀️" },
  { key: "moon", label: "Moon", glyph: "🌙" },
  { key: "rainbow", label: "Rainbow", glyph: "🌈" },
  { key: "cloud", label: "Cloud", glyph: "☁️" },
  { key: "snowflake", label: "Snowflake", glyph: "❄️" },
  { key: "tornado", label: "Tornado", glyph: "🌪️" },
  { key: "wave", label: "Wave", glyph: "🌊" },
  { key: "mountain", label: "Mountain", glyph: "🏔️" },
  { key: "tree", label: "Tree", glyph: "🌲" },
  { key: "flower", label: "Flower", glyph: "🌸" },
  { key: "seedling", label: "Seedling", glyph: "🌱" },
  { key: "mushroom", label: "Mushroom", glyph: "🍄" },
  { key: "leaf", label: "Leaf", glyph: "🍃" },
  { key: "cactus", label: "Cactus", glyph: "🌵" },
  // Food & drink
  { key: "coffee", label: "Coffee", glyph: "☕" },
  { key: "pizza", label: "Pizza", glyph: "🍕" },
  { key: "taco", label: "Taco", glyph: "🌮" },
  { key: "ice-cream", label: "Ice cream", glyph: "🍦" },
  { key: "cookie", label: "Cookie", glyph: "🍪" },
  { key: "candy", label: "Candy", glyph: "🍬" },
  { key: "fruit", label: "Fruit", glyph: "🍎" },
  { key: "avocado", label: "Avocado", glyph: "🥑" },
  // Misc
  { key: "heart", label: "Heart", glyph: "❤️" },
  { key: "party", label: "Party", glyph: "🎉" },
  { key: "balloon", label: "Balloon", glyph: "🎈" },
  { key: "gift", label: "Gift", glyph: "🎁" },
  { key: "pin", label: "Pin", glyph: "📌" },
  { key: "paperclip", label: "Paperclip", glyph: "📎" },
  { key: "bulb", label: "Light bulb", glyph: "💡" },
  { key: "megaphone", label: "Megaphone", glyph: "📣" },
  { key: "bell", label: "Bell", glyph: "🔔" },
  { key: "no-bell", label: "Muted bell", glyph: "🔕" },
  { key: "link", label: "Link", glyph: "🔗" },
  { key: "chain", label: "Chain", glyph: "⛓️" },
  { key: "anchor", label: "Anchor", glyph: "⚓" },
  { key: "plane", label: "Plane", glyph: "✈️" },
  { key: "car", label: "Car", glyph: "🚗" },
  { key: "train", label: "Train", glyph: "🚂" },
  { key: "ship", label: "Ship", glyph: "🚢" },
  { key: "umbrella", label: "Umbrella", glyph: "☂️" },
  { key: "map", label: "Map", glyph: "🗺️" },
  { key: "pinwheel", label: "Pinwheel", glyph: "🪁" },
];

export function botIconFor(key: string | null | undefined): BotIconOption {
  return BOT_ICONS.find((icon) => icon.key === key) ?? BOT_ICONS[0];
}
